name: Deploy Backend to Azure Web App
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'startup.sh'  # Add this to ensure changes to startup.sh trigger deployment
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # Changed from 3.13 to 3.10 for better Azure compatibility
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Check for requirements.txt in multiple locations
        if [ -f "backend/requirements.txt" ]; then
          pip install -r backend/requirements.txt
        elif [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found"
          exit 1
        fi
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'napnap'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./  # Deploy entire repository
