name: Azure Backend Web App CI/CD TEST

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Debug directory structure
        run: |
          echo "Current working directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Backend directory contents:"
          ls -la backend || echo "Backend directory not found"
          echo "Requirements.txt locations:"
          find . -name "requirements.txt" -type f
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          if [ -f "backend/requirements.txt" ]; then
            echo "Found requirements.txt in backend directory"
            pip install -r backend/requirements.txt
          elif [ -f "requirements.txt" ]; then
            echo "Found requirements.txt in root directory"
            pip install -r requirements.txt
          else
            REQUIREMENTS_FILE=$(find . -name "requirements.txt" -type f | head -n 1)
            if [ -n "$REQUIREMENTS_FILE" ]; then
              echo "Found requirements.txt at: $REQUIREMENTS_FILE"
              pip install -r "$REQUIREMENTS_FILE"
            else
              echo "ERROR: requirements.txt not found anywhere in repository"
              exit 1
            fi
          fi
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'napnap'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          action: "close"
